// Generated by CoffeeScript 1.8.0
(function() {
  module.exports = {

    /* IndexController.index() */
    index: function(req, res, next) {
      var async;
      async = require('async');
      return async.parallel([
        function(callback) {
          return Events.find().sort({
            _id: 'desc'
          }).exec(function(error, events) {
            if (error) {
              next(error);
            }
            return callback(null, events);
          });
        }, function(callback) {
          return Settings.find().limit(1).exec(function(error, settings) {
            if (error) {
              next(error);
            }
            return callback(null, settings);
          });
        }
      ], function(error, results) {
        if (error) {
          next(error);
        }
        return res.view('homepage', {
          events: results[0],
          settings: results[1][0]
        });
      });
    }
  };

}).call(this);
