// Generated by CoffeeScript 1.8.0
(function() {
  module.exports = {
    index: function(req, res) {
      return Events.find().sort({
        _id: 'desc'
      }).exec(function(error, events) {
        if (error) {
          next(error);
        }
        return res.view('homepage', {
          events: events
        });
      });
    }
  };

}).call(this);
