// Generated by CoffeeScript 1.8.0
(function() {
  module.exports = {

    /* NotificationsController.index() */
    index: function(req, res, next) {
      return res.view({
        title: 'Notifications'
      });
    }
  };

}).call(this);
