// Generated by CoffeeScript 1.8.0
(function() {
  module.exports = {

    /* SettingsController.index() */
    index: function(req, res) {
      return res.json({
        todo: 'GET /settings'
      });
    }
  };

}).call(this);
