// Generated by CoffeeScript 1.8.0
(function() {
  module.exports = {

    /* UsersController.index() */

    /* UsersController.create() */

    /* UsersControler.login() */
    index: function(req, res, next) {
      return res.redirect('/');
    },
    login: function(req, res, next) {
      var md5, params;
      params = req.params.all();
      md5 = require('MD5');
      return Users.find({
        email: params.email,
        password: md5(params.password)
      }).limit(1).exec(function(error, user) {
        if (error || Object.keys(user).length <= 0) {
          return res.view({
            error: 'Email or password is invalid'
          });
        }
        req.session.isAdmin = true;
        req.session.user = user[0];
        return res.redirect('/events');
      });
    },

    /* UsersController.logout() */
    logout: function(req, res, next) {
      delete req.session.isAdmin;
      delete req.session.user;
      return res.redirect('/');
    },
    profile: function(req, res, next) {
      var params;
      if (req.method === 'POST') {
        params = req.params.all();
        Users.find().limit(1).exec(function(error, user, next) {
          if (error) {
            return next(error);
          }
          Users.update(user[0], params, {
            upsert: true
          }).exec(function(error, updateStatus) {
            if (error && error.invalidAttributes) {
              return req.flash('errors', MyServices.modelValidation(Users, error.invalidAttributes));
            } else {
              return req.flash('message', 'Update profile successfull');
            }
          });
          return res.redirect('/profile');
        });
      }
      return Users.find().limit(1).exec(function(error, user) {
        if (error) {
          return next(error);
        }
        return res.view({
          title: 'Profile update',
          user: user[0]
        });
      });
    }
  };

}).call(this);
